import type { Person, Project } from "./types";

export const people: Person[] = [
  { id: "m-schneider", name: "M. Schneider", role: "Projektleiter", initials: "MS", tone: "navy" },
  { id: "j-wegner", name: "J. Wegner", role: "Satz", initials: "JW", tone: "blue" },
  { id: "l-bauer", name: "L. Bauer", role: "Korrektorat", initials: "LB", tone: "orange" },
  { id: "s-klein", name: "S. Klein", role: "Autor", initials: "SK", tone: "green" },
  { id: "s-reuter", name: "S. Reuter", role: "Redaktion", initials: "SR", tone: "violet" },
];

export const projects: Project[] = [
  {
    id: "kunst-des-satzes",
    title: "Die Kunst des Satzes",
    publisher: "Verlag Zukunft",
    isbn: "978-3-123456-78-9",
    titleNumber: "VZ-2026-0418",
    pages: 312,
    deadline: "2026-07-24",
    deadlineLabel: "24.07.2026",
    progress: 72,
    status: "im-satz",
    risk: "mittel",
    compositionProfile: "image-led",
    profileWorkload: [
      { profileId: "linear", plannedPages: 150, actualPages: 122, completedPages: 112, issueCount: 0 },
      { profileId: "image-led", plannedPages: 126, actualPages: 142, completedPages: 96, issueCount: 3 },
      { profileId: "complex", plannedPages: 36, actualPages: 48, completedPages: 17, issueCount: 4 },
    ],
    phase: "Autorenkorrektur",
    leadId: "m-schneider",
    team: ["m-schneider", "j-wegner", "l-bauer", "s-klein"],
    blocker: "3 offene Korrekturhinweise in Kapitel 4",
    chapters: [
      {
        id: "kds-1",
        title: "Einleitung",
        pages: "1-24",
        ownerId: "j-wegner",
        status: "im-satz",
        correctionRound: "V2",
        risk: "niedrig",
      },
      {
        id: "kds-2",
        title: "Grundlagen",
        pages: "25-68",
        ownerId: "j-wegner",
        status: "im-satz",
        correctionRound: "V2",
        risk: "niedrig",
      },
      {
        id: "kds-3",
        title: "Typografie",
        pages: "69-122",
        ownerId: "l-bauer",
        status: "im-satz",
        correctionRound: "Autorenkorrektur",
        risk: "mittel",
      },
      {
        id: "kds-4",
        title: "Layout & Struktur",
        pages: "123-184",
        ownerId: "s-klein",
        status: "in-korrektur",
        correctionRound: "Autorenkorrektur",
        blocker: "Bildlegenden fehlen",
        risk: "hoch",
      },
      {
        id: "kds-5",
        title: "Praxis & Beispiele",
        pages: "185-268",
        ownerId: "j-wegner",
        status: "offen",
        correctionRound: "V1",
        risk: "mittel",
      },
      {
        id: "kds-6",
        title: "Anhang",
        pages: "269-312",
        ownerId: "s-reuter",
        status: "offen",
        correctionRound: "V1",
        risk: "niedrig",
      },
    ],
    correctionSteps: [
      { id: "v1", label: "V1", owner: "Erstsatz", date: "08.07.", state: "done", note: "Erfassung erstellt" },
      { id: "v2", label: "V2", owner: "Autor Review", date: "12.07.", state: "done", note: "Abgeschlossen von S. Klein" },
      {
        id: "autorenkorrektur",
        label: "Autorenkorrektur",
        owner: "S. Klein",
        date: "15.07.",
        state: "active",
        note: "In Bearbeitung",
      },
      {
        id: "schlusskorrektur",
        label: "Schlusskorrektur",
        owner: "Redaktion",
        date: "19.07.",
        state: "planned",
        note: "Geplant",
      },
      {
        id: "freigabe",
        label: "Freigabe",
        owner: "Herstellung",
        date: "22.07.",
        state: "planned",
        note: "Ausstehend",
      },
    ],
    comments: [
      {
        id: "c1",
        author: "S. Klein",
        role: "Autor",
        date: "15.07.",
        chapter: "Kapitel 4, Seite 98",
        text: "Bitte Bildunterschrift präzisieren.",
      },
      {
        id: "c2",
        author: "L. Bauer",
        role: "Korrektorat",
        date: "15.07.",
        chapter: "Kapitel 4, Seite 102",
        text: "Komma nach Absatz 3 entfernen.",
      },
    ],
    preflight: [
      { id: "pdfx", label: "PDF/X-Konformität", state: "passed", details: "Erfüllt" },
      { id: "fonts", label: "Schriften eingebettet", state: "passed", details: "Erfüllt" },
      { id: "wcag", label: "Barrierefreiheit WCAG 2.1", state: "warning", details: "3 Hinweise" },
      { id: "images", label: "Bildauflösung", state: "passed", details: "Erfüllt" },
      { id: "colors", label: "Farbraum & Transparenzen", state: "passed", details: "Erfüllt" },
      { id: "links", label: "Links & Interaktivität", state: "passed", details: "Erfüllt" },
      { id: "meta", label: "Dokumentinformationen", state: "passed", details: "Erfüllt" },
    ],
    timeline: [
      { label: "Satz", status: "im-satz", startWeek: 20, endWeek: 23 },
      { label: "Korrektur", status: "in-korrektur", startWeek: 22, endWeek: 25 },
      { label: "Preflight", status: "preflight", startWeek: 25, endWeek: 26 },
    ],
  },
  {
    id: "digital-mindset",
    title: "Digital Mindset",
    publisher: "Nova Books",
    isbn: "978-3-445566-10-4",
    titleNumber: "NB-2026-1027",
    pages: 248,
    deadline: "2026-07-10",
    deadlineLabel: "10.07.2026",
    progress: 45,
    status: "in-korrektur",
    risk: "hoch",
    compositionProfile: "linear",
    profileWorkload: [
      { profileId: "linear", plannedPages: 210, actualPages: 198, completedPages: 90, issueCount: 1 },
      { profileId: "image-led", plannedPages: 38, actualPages: 42, completedPages: 20, issueCount: 2 },
      { profileId: "complex", plannedPages: 0, actualPages: 8, completedPages: 2, issueCount: 1 },
    ],
    phase: "V2 blockiert",
    leadId: "s-reuter",
    team: ["s-reuter", "j-wegner", "l-bauer"],
    blocker: "Autorenfeedback seit 4 Tagen überfällig",
    chapters: [
      {
        id: "dm-1",
        title: "Digitale Grundlagen",
        pages: "1-82",
        ownerId: "j-wegner",
        status: "in-korrektur",
        correctionRound: "V2",
        risk: "mittel",
      },
      {
        id: "dm-2",
        title: "Transformation im Team",
        pages: "83-160",
        ownerId: "l-bauer",
        status: "in-korrektur",
        correctionRound: "V2",
        blocker: "Autorenfeedback offen",
        risk: "hoch",
      },
    ],
    correctionSteps: [
      { id: "dm-v1", label: "V1", owner: "Satz", date: "28.06.", state: "done", note: "Erstsatz geliefert" },
      {
        id: "dm-v2",
        label: "V2",
        owner: "Autor Review",
        date: "04.07.",
        state: "active",
        note: "Rückmeldung überfällig",
      },
    ],
    comments: [],
    preflight: [
      { id: "dm-pdfx", label: "PDF/X-Konformität", state: "warning", details: "Final-PDF ausstehend" },
      { id: "dm-fonts", label: "Schriften eingebettet", state: "passed", details: "Erfüllt" },
    ],
    timeline: [
      { label: "Satz", status: "im-satz", startWeek: 19, endWeek: 21 },
      { label: "Korrektur", status: "in-korrektur", startWeek: 21, endWeek: 25 },
    ],
  },
  {
    id: "nachhaltig-handeln",
    title: "Nachhaltig handeln",
    publisher: "Grün Verlag",
    isbn: "978-3-445566-88-6",
    titleNumber: "GV-2026-2304",
    pages: 196,
    deadline: "2026-08-02",
    deadlineLabel: "02.08.2026",
    progress: 88,
    status: "preflight",
    risk: "niedrig",
    compositionProfile: "image-led",
    profileWorkload: [
      { profileId: "linear", plannedPages: 100, actualPages: 84, completedPages: 80, issueCount: 0 },
      { profileId: "image-led", plannedPages: 80, actualPages: 94, completedPages: 80, issueCount: 1 },
      { profileId: "complex", plannedPages: 16, actualPages: 18, completedPages: 12, issueCount: 0 },
    ],
    phase: "Preflight",
    leadId: "m-schneider",
    team: ["m-schneider", "s-reuter"],
    chapters: [
      {
        id: "nh-1",
        title: "Klimabilanz",
        pages: "1-74",
        ownerId: "s-reuter",
        status: "preflight",
        correctionRound: "Freigabe",
        risk: "niedrig",
      },
      {
        id: "nh-2",
        title: "Praxisleitfaden",
        pages: "75-154",
        ownerId: "m-schneider",
        status: "preflight",
        correctionRound: "Freigabe",
        risk: "niedrig",
      },
    ],
    correctionSteps: [
      { id: "nh-v1", label: "V1", owner: "Redaktion", date: "18.07.", state: "done", note: "Abgeschlossen" },
      { id: "nh-freigabe", label: "Freigabe", owner: "Herstellung", date: "27.07.", state: "active", note: "Preflight prüft" },
    ],
    comments: [],
    preflight: [
      { id: "pdfx", label: "PDF/X-Konformität", state: "passed", details: "Erfüllt" },
      { id: "fonts", label: "Schriften eingebettet", state: "passed", details: "Erfüllt" },
      { id: "wcag", label: "Barrierefreiheit WCAG 2.1", state: "warning", details: "Alt-Texte prüfen" },
      { id: "images", label: "Bildauflösung", state: "passed", details: "Erfüllt" },
      { id: "colors", label: "Farbraum & Transparenzen", state: "passed", details: "Erfüllt" },
      { id: "links", label: "Links & Interaktivität", state: "passed", details: "Erfüllt" },
      { id: "meta", label: "Dokumentinformationen", state: "passed", details: "Erfüllt" },
    ],
    timeline: [{ label: "Preflight", status: "preflight", startWeek: 22, endWeek: 25 }],
  },
  {
    id: "storytelling-heute",
    title: "Storytelling heute",
    publisher: "Vision Media",
    isbn: "978-3-987654-12-3",
    titleNumber: "VM-2026-0712",
    pages: 276,
    deadline: "2026-07-18",
    deadlineLabel: "18.07.2026",
    progress: 25,
    status: "im-satz",
    risk: "mittel",
    compositionProfile: "complex",
    profileWorkload: [
      { profileId: "linear", plannedPages: 84, actualPages: 60, completedPages: 26, issueCount: 0 },
      { profileId: "image-led", plannedPages: 124, actualPages: 104, completedPages: 26, issueCount: 3 },
      { profileId: "complex", plannedPages: 68, actualPages: 112, completedPages: 17, issueCount: 6 },
    ],
    phase: "Satz",
    leadId: "j-wegner",
    team: ["j-wegner", "l-bauer"],
    chapters: [
      {
        id: "sh-1",
        title: "Grundlagen des Erzählens",
        pages: "1-96",
        ownerId: "j-wegner",
        status: "im-satz",
        correctionRound: "V1",
        risk: "mittel",
      },
      {
        id: "sh-2",
        title: "Formate und Kanäle",
        pages: "97-188",
        ownerId: "j-wegner",
        status: "offen",
        correctionRound: "V1",
        risk: "mittel",
      },
    ],
    correctionSteps: [
      { id: "sh-satz", label: "Satz", owner: "J. Wegner", date: "05.07.", state: "active", note: "Kapitel 1 im Satz" },
      { id: "sh-v1", label: "V1", owner: "Korrektorat", date: "12.07.", state: "planned", note: "Geplant" },
    ],
    comments: [],
    preflight: [
      { id: "sh-pdfx", label: "PDF/X-Konformität", state: "warning", details: "Noch nicht final" },
      { id: "sh-images", label: "Bildauflösung", state: "passed", details: "Vorabcheck bestanden" },
    ],
    timeline: [{ label: "Satz", status: "im-satz", startWeek: 21, endWeek: 23 }],
  },
  {
    id: "design-thinking",
    title: "Design Thinking im Unterricht",
    publisher: "Nova Books",
    isbn: "978-3-101010-55-1",
    titleNumber: "NB-2026-1160",
    pages: 224,
    deadline: "2026-08-29",
    deadlineLabel: "29.08.2026",
    progress: 10,
    status: "offen",
    risk: "niedrig",
    compositionProfile: "image-led",
    profileWorkload: [
      { profileId: "linear", plannedPages: 96, actualPages: 96, completedPages: 12, issueCount: 0 },
      { profileId: "image-led", plannedPages: 104, actualPages: 104, completedPages: 9, issueCount: 0 },
      { profileId: "complex", plannedPages: 24, actualPages: 24, completedPages: 1, issueCount: 0 },
    ],
    phase: "Manuskript",
    leadId: "m-schneider",
    team: ["m-schneider"],
    chapters: [
      {
        id: "dt-1",
        title: "Methodenüberblick",
        pages: "1-64",
        ownerId: "m-schneider",
        status: "offen",
        correctionRound: "Manuskript",
        risk: "niedrig",
      },
      {
        id: "dt-2",
        title: "Unterrichtspraxis",
        pages: "65-142",
        ownerId: "m-schneider",
        status: "offen",
        correctionRound: "Manuskript",
        risk: "niedrig",
      },
    ],
    correctionSteps: [
      { id: "dt-manuskript", label: "Manuskript", owner: "Redaktion", date: "24.07.", state: "active", note: "Eingang prüfen" },
      { id: "dt-satz", label: "Satz", owner: "Herstellung", date: "05.08.", state: "planned", note: "Geplant" },
    ],
    comments: [],
    preflight: [
      { id: "dt-fonts", label: "Schriften eingebettet", state: "passed", details: "Template geprüft" },
      { id: "dt-meta", label: "Dokumentinformationen", state: "warning", details: "Metadaten offen" },
    ],
    timeline: [{ label: "Manuskript", status: "offen", startWeek: 20, endWeek: 22 }],
  },
];
